version: '3.8'

services:
  crud-app:
    build:
      context: ./crudap
      dockerfile: Dockerfile
    container_name: crud-app
    env_file:
      - ./crudap/.env
    ports:
      - "8080:8080"
    environment:
      DB_HOST: crud-db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: 12212332
      JWT_SECRET: jwt_secret
      JWT_EXPIRATION: 360000
      SERVER_PORT: 8080
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      crud-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - app-network

  crud-db:
    image: postgres:15.3-alpine
    container_name: crud-db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12212332
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - crud-postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  notification-app:
    build:
      context: ./notification
      dockerfile: Dockerfile
    container_name: notification-app
    ports:
      - "8081:8080"
    environment:
      SPRING_APPLICATION_NAME: notification
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - app-network

  subscription-app:
    build:
      context: ./subscription
      dockerfile: Dockerfile
    container_name: subscription-app
    ports:
      - "8082:8080"
    environment:
      SERVER_PORT: 8080
      DB_HOST: subscription-db
      DB_PORT: 5432
      DB_NAME: subscriptiondb
      DB_USER: postgres
      DB_PASSWORD: 12212332
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      subscription-db:
        condition: service_healthy
      kafka:
        condition: service_healthy
    networks:
      - app-network

  subscription-db:
    image: postgres:15.3-alpine
    container_name: subscription-db
    restart: always
    environment:
      POSTGRES_DB: subscriptiondb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12212332
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - subscription-postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    # ports:
    # - "9093:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server kafka:9092"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  crud-postgres-data:
  subscription-postgres-data:
